version: "3.4"

services:
  s3-stub:
    image: localstack/localstack
    environment:
      - SERVICES=s3:4566
      - DEFAULT_REGION=eu-west-1
      - S3_PORT=4566
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - 4566:4566
    volumes:
      - ./stubs/s3:/var/lib/localstack
